_base_ = 'cwd_bbop_fpnlvl_frcnn_r50_lka_fpn_frcnn_r18_lka_fpn_1x_VisDrone640.py'

algorithm = dict(
    type='GeneralDistill',
    distiller=dict(
        components=[
            dict(
                student_module='neck.fpn_convs.3.conv',
                teacher_module='neck.fpn_convs.3.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_3',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
            dict(
                student_module='neck.fpn_convs.2.conv',
                teacher_module='neck.fpn_convs.2.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_2',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
            dict(
                student_module='neck.fpn_convs.1.conv',
                teacher_module='neck.fpn_convs.1.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_1',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
            dict(
                student_module='neck.fpn_convs.0.conv',
                teacher_module='neck.fpn_convs.0.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_0',
                        tau=1,
                        loss_weight=5,
                    )
                ]),

            dict(
                student_module='neck.fpn_att_convs.3.att_conv_relu.conv',
                teacher_module='neck.fpn_att_convs.3.att_conv_relu.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_att_3',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
            dict(
                student_module='neck.fpn_att_convs.2.att_conv_relu.conv',
                teacher_module='neck.fpn_att_convs.2.att_conv_relu.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_att_2',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
            dict(
                student_module='neck.fpn_att_convs.1.att_conv_relu.conv',
                teacher_module='neck.fpn_att_convs.1.att_conv_relu.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_att_1',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
            dict(
                student_module='neck.fpn_att_convs.0.att_conv_relu.conv',
                teacher_module='neck.fpn_att_convs.0.att_conv_relu.conv',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_fpn_att_0',
                        tau=1,
                        loss_weight=5,
                    )
                ]),
        ]),
    )